Update docker image

diff --git a/examples/with-magic-with-docker/Dockerfile b/examples/with-magic-with-docker/Dockerfile
--- a/examples/with-magic-with-docker/Dockerfile
+++ b/examples/with-magic-with-docker/Dockerfile
@@ -1,19 +1,57 @@
-# base image
-FROM node:16.13-alpine
 
-# Create and change to the app directory.
-WORKDIR /usr/app
+# Install dependencies only when needed
+FROM node:16-alpine AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-# Copy application dependency manifests to the container image.
-# A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
-# Copying this first prevents re-running npm install on every code change.
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+
+# Rebuild the source code only when needed
+FROM node:16-alpine AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-# Install production dependencies.
-# If you add a package-lock.json, speed your build by switching to 'npm ci'.
-RUN npm ci --only=production
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
 
-# Generate envirorment variables from arguments
+RUN yarn build
+
+# If using npm comment out above and use below instead
+# RUN npm run build
+
+# Production image, copy all the files and run next
+FROM node:16-alpine AS runner
+WORKDIR /app
+
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
+EXPOSE 3000
 
 ARG MAGIC_TOKEN
 ARG NEXT_PUBLIC_MAGIC_PUB_TOKEN
@@ -24,10 +62,11 @@ ENV MAGIC_TOKEN=$MAGIC_TOKEN
 ENV NEXT_PUBLIC_MAGIC_PUB_TOKEN=$NEXT_PUBLIC_MAGIC_PUB_TOKEN
 ENV MAGIC_ENCRYPTION_SECRET=$MAGIC_ENCRYPTION_SECRET
 ENV NEXT_PUBLIC_IS_PROTECTED=$NEXT_PUBLIC_IS_PROTECTED
+ENV PORT 3000
 
-# Copy local code to the container image.
+CMD ["node", "server.js"]
 
-RUN npm run build
+# Generate envirorment variables from arguments
 
-# Run the web service on container startup.
-CMD [ "npm", "start" ]
+
+
